PRODUCT_VERSION_MAJOR = 14
PRODUCT_VERSION_MINOR = 0

# Increase PIXELSTAR Version with each major release.
PIXELSTAR_VERSION := 4.0
PIXELSTAR_BUILD_TYPE ?= Unofficial

# Set all versions
BUILD_DATE := $(shell date -u +%Y%m%d)
BUILD_TIME := $(shell date -u +%H%M)

# Internal version
LINEAGE_VERSION := Pixelstar-V$(PIXELSTAR_VERSION)-$(LINEAGE_BUILD)-$(PIXELSTAR_BUILD_TYPE)-$(BUILD_TIME)-$(BUILD_DATE)

# Display version
LINEAGE_DISPLAY_VERSION := Pixelstar-$(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR)-$(LINEAGE_BUILD)-v$(PIXELSTAR_VERSION)
