PRODUCT_VERSION_MAJOR = 14
PRODUCT_VERSION_MINOR = 0

# Increase PIXELSTAR Version with each major release.
PIXELSTAR_VERSION := 4.0
PIXELSTAR_BUILD_TYPE ?= Unofficial

# Internal version
LINEAGE_VERSION := Pixelstar-$(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR)-$(shell date +%Y%m%d)-$(LINEAGE_BUILD)-v$(PIXELSTAR_VERSION)-$(PIXELSTAR_BUILD_TYPE)

# Display version
LINEAGE_DISPLAY_VERSION := Pixelstar-$(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR)-$(LINEAGE_BUILD)-v$(PIXELSTAR_VERSION)
